version: "3.8"
services:
  app:
    container_name: service
    build:
      context: .
      target: Production
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - redis
      - mongo
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db